using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Generic;

// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>SisulaGUI</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>True</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SisulaGUI.Model
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Source
    {

        private string descriptionField;

        private List<sourcePart> partField;

        private string nameField;

        private string codepageField;

        private string datafiletypeField;

        private string fieldterminatorField;

        private short rowlengthField;

        private bool rowlengthFieldSpecified;

        private string splitField;

        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string description { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codepage { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datafiletype { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldterminator { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short rowlength { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rowlengthSpecified { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string split { get; set; }


        public Source()
        {
            this.partField = new List<sourcePart>();
        }

        [System.Xml.Serialization.XmlElementAttribute("part")]
        public List<sourcePart> part
        {
            get
            {
                return this.partField;
            }
            set
            {
                this.partField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class sourcePart
    {

        private List<object> itemsField;

        private List<string> textField;

        private string nameField;

        private string nullsField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string nulls { get; set; }


        public sourcePart()
        {
            this.textField = new List<string>();
            this.itemsField = new List<object>();
        }

        [System.Xml.Serialization.XmlElementAttribute("calculation", typeof(sourcePartCalculation))]
        [System.Xml.Serialization.XmlElementAttribute("key", typeof(sourcePartKey))]
        [System.Xml.Serialization.XmlElementAttribute("term", typeof(sourcePartTerm))]
        public List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public List<string> Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class sourcePartCalculation
    {

        private string nameField;

        private string formatField;

        private string persistedField;

        private string patternField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string persisted { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pattern { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class sourcePartKey
    {

        private List<sourcePartKeyComponent> componentField;

        private string nameField;

        private string typeField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type { get; set; }


        public sourcePartKey()
        {
            this.componentField = new List<sourcePartKeyComponent>();
        }

        [System.Xml.Serialization.XmlElementAttribute("component")]
        public List<sourcePartKeyComponent> component
        {
            get
            {
                return this.componentField;
            }
            set
            {
                this.componentField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class sourcePartKeyComponent
    {

        private string ofField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string of { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class sourcePartTerm
    {

        private string nameField;

        private string delimiterField;

        private string formatField;

        private string patternField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string delimiter { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string format { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pattern { get; set; }

        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

    }
}
